name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        #os: ['ubuntu-latest', 'windows-latest']
        os: ['ubuntu-latest']
        ruby-version: ['2.7', '3.0', '3.1']

    name: Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install addons
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libgmp3-dev libcap-ng-dev

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test TESTOPTS=-v
